### ISSUE TITLE
importing arw file

### ISSUE THREAD

**Issue by crestre** [ethanbass/chromatographR#26] opened 2023-07-19 15:15 UTC
I am importing an .arw file using chromConveter and I am getting the following message:

Warning messages:

1: In strsplit(readLines(file, n = 2), "\t") :
  unable to translate '"PDA Exposure Time"	"Processing Locked"	"Sampling Rate"	"Scale to <b5>V"	"Source S/W Info"	"Det. Units"	"Data Start"	"Data End"	"Channel Type"	"Channel Status"	"Channel Id"	"Channel Description"	"Channel"	"# of Results Stored"' to a wide string
2: In strsplit(readLines(file, n = 2), "\t") : input string 1 is invalid

Your help would be more than appreciated.
Carla

**Comment by ethanbass** [comment] 2023-07-19 20:28
Hi Carla,
I'd be happy to take a look. Do you think you could send me the file in question? You could attach it here or email it to me. Also what version of chromConverter are you running? You can check with packageVersion("chromConverter") in the R console.
Ethan

**Comment by crestre** [comment] 2023-07-19 23:40
[Siderophoros AIA1622.arw.zip](https://github.com/ethanbass/chromatographR/files/12100836/Siderophoros.AIA1622.arw.zip)

Hi Ethan, 

Thanks for your prompt reply. I am attaching the file that we used with  chromConverter version 0.2.1
Carla

**Comment by ethanbass** [comment] 2023-07-20 03:27
Thank you very much for providing the file. It turns out there were actually a couple of problems. The error you were getting was caused by a stray unicode character, but also your file is from a PDA detector which wasn't supported by the parser up to now because I didn't have any example files to work with. I added a few lines to the parser that seem to resolve both issues.

You can try installing the latest version of chromConverter from GitHub with the fix (https://github.com/ethanbass/chromConverter/commit/f99f4b124c9887fbe7c01c1839e35ceb53d82059) using the install_github function from the remotes package (e.g. `remotes::install_github("ethanbass/chromConverter"`). You will also need to restart your R session to clear the old package from the cache. I think the new parser should be able to read your files correctly but please let me know if you run into any more issues or notice any problems with the output. The file you sent is the only example I have of an arw file from a PDA detector so it's possible there could be something I'm missing.

all best,
Ethan

**Comment by ethanbass** [comment] 2023-07-25 13:13
Curious if you got this working?

**Comment by ethanbass** [comment] 2023-08-20 21:59
I am going to close this issue for now, as I believe it has been resolved by ethanbass/chromConverter@f99f4b1. Feel free to reopen if you're still having any issues. Thanks!
Ethan

**Closed by ethanbass** 2023-08-20 21:59 UTC

**Comment by crestre** [comment] 2023-09-03 14:05
Ethan, 
Finally I was able to check into this and it worked! Thanks a lot.  I have some questions but I will open a new issue.
